### ISSUE TITLE
nfRendererOGL4: Multiple OpenGL contexts

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#151]
Supporting multiple OS windows requires nfRendererOGL4 to perform switching between contexts. Of course, the situation varies between platforms - resource sharing between contexts is differently implemented, plus OpenGL Extensions must be handled in a different way.

Linux seems to have a slightly easier to handle ABI, so it would be a good starting point.

**Task list:**
- [x] Add a Context singleton, which will perform following actions:
  - [x] Allocate a main OpenGL Context (aka. Master Context).
  - [x] Expose data needed to create per-Backbuffer contexts (aka. Slave Contexts) in a multi-platform way.
  - [x] Implement the solution on Linux only, as Extensions there do not depend on Contexts.
- [x] Port the solution to Windows:
  - [x] Master Context and Slave Context implementation on Windows.
  - [x] OpenGL Extensions on Windows are context-dependent, so each created context should have its own OGL Extension pointer set.

**Comment by Witek902** [comment]
Why "context singleton"? "Master context" should be kept inside Device object. Theoretically, we could create multiple devices, so each must have its own master context.

**Comment by lookeypl** [comment]
I didn't know about this assumption. It makes sharing the Master Context a bit problematic, however I will try to reorganize the design. I wanted to introduce a new class just to make the organization inside the code clear.

BTW do we really need to support creation of multiple devices? What will be the use case?

**Comment by Witek902** [comment]
My bad, there will be only 1 device:
https://github.com/nfprojects/nfengine/blob/devel/nfEngine/Renderers/nfRendererD3D11/RendererD3D11.cpp#L13
But keep in mind that after calling _Release()_ function the master context must be also released (classic singletons implemented as static object are destroyed when the whole application exits).

**Comment by lookeypl** [comment]
OK, will get done. It is already late-initialized (by Init method) so adding a Release method won't be a problem.

**Comment by lookeypl** [comment]
https://review.gerrithub.io/#/c/262583/
https://review.gerrithub.io/#/c/265300/

Merged, closing.
